import { readFileSync } from 'node:fs';
import path from 'node:path';
import { Controller, Get, Header, Logger, NotFoundException } from '@nestjs/common';

/**
 * Serves the generated OpenAPI document.
 *
 * The file is read from disk rather than imported so that `resolveJsonModule`
 * is not needed and the spec is not baked into the bundle - it is a build
 * artefact generated by scripts/openapi-generate.mjs, not source.
 *
 * Read once and cached: the document is ~6000 lines and does not change while
 * the process is running.
 */
@Controller()
export class OpenApiController {
  private readonly logger = new Logger(OpenApiController.name);
  private cached?: string;

  @Get('openapi.json')
  @Header('Content-Type', 'application/json')
  @Header('Cache-Control', 'public, max-age=300')
  getSpec(): string {
    if (this.cached) {
      return this.cached;
    }

    const spec = loadSpec();

    if (!spec) {
      // A missing spec is a packaging mistake, not a client error, so it is
      // logged rather than passed over in silence.
      this.logger.warn('openapi.json was not found; the spec was not generated before packaging');
      throw new NotFoundException('OpenAPI document is not available in this build');
    }

    this.cached = spec;
    return spec;
  }
}

/**
 * Tries the locations the file occupies in a container and in a dev checkout.
 * Exported so the resolution order is testable rather than discovered in prod.
 */
export function specSearchPaths(baseDir: string = __dirname): string[] {
  return [
    // Container: dist/api/ -> /app/docs/api/openapi.json
    path.resolve(baseDir, '../../../../docs/api/openapi.json'),
    // Dev: src/api/ -> repo root docs/api/openapi.json
    path.resolve(baseDir, '../../../../../docs/api/openapi.json'),
    path.resolve(process.cwd(), 'docs/api/openapi.json'),
  ];
}

function loadSpec(): string | undefined {
  for (const candidate of specSearchPaths()) {
    try {
      // eslint-disable-next-line security/detect-non-literal-fs-filename -- Reviewed 2026-09-03: candidates are a fixed, code-defined list derived from __dirname and cwd, never from user input or request data; see docs/SECURITY-SUPPRESSIONS.md.
      return readFileSync(candidate, 'utf8');
    } catch {
      // Try the next location.
    }
  }

  return undefined;
}
